# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lnet < Formula
  desc ""
  homepage "https://github.com/louislef299/lnet"
  version "1.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/louislef299/lnet/releases/download/v1.4.0/lnet_1.4.0_Darwin_arm64.tar.gz"
      sha256 "9d7e039012c2e88e50476a3ab31bda246c4ae0fea864325249e976012a7e2a2f"

      def install
        bin.install "lnet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/lnet/releases/download/v1.4.0/lnet_1.4.0_Darwin_x86_64.tar.gz"
      sha256 "4bc7b9a0e822aae93238dc2d9679770f5b9840c5d8760a05038ccfe2131a4664"

      def install
        bin.install "lnet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/lnet/releases/download/v1.4.0/lnet_1.4.0_Linux_arm64.tar.gz"
      sha256 "ba17f4801e44629cea381f4ac19eba330e3a4f00ed49e7a897bcbace4e549935"

      def install
        bin.install "lnet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/louislef299/lnet/releases/download/v1.4.0/lnet_1.4.0_Linux_x86_64.tar.gz"
      sha256 "212c48ab28938c866f553ecdd8377326e888e8178f07f5d384602badc99494a2"

      def install
        bin.install "lnet"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/louislef299/lnet/releases/download/v1.4.0/lnet_1.4.0_Linux_arm.tar.gz"
      sha256 "a0918debc073c0b50ab5362346aaab59c10024803462d9a8e7a139fc3e2955f5"

      def install
        bin.install "lnet"
      end
    end
  end
end
